[package]
name = "xevm_engine"
version = "0.1.0"
authors = []
edition = "2021"
description = ""
documentation = ""
readme = false
homepage = ""
repository = ""
license = ""
publish = false
autobenches = false
build = "../build.rs"

[lib]
crate_type = ["rlib", "staticlib"]

[dependencies]
engine-precompiles = { path = "../engine-precompiles", default-features = false }
engine-sdk = { path = "../engine-sdk", default-features = false }
engine-transactions = { path = "../engine-transactions", default-features = false }
engine-types = { path = "../engine-types", default-features = false }
borsh = { version = "0.8.2", default-features = false }
evm = { git = "https://github.com/rust-blockchain/evm.git", rev = "07ae4451bb1d8d1cc81e5e07685691e68220a7d2", default-features = false }
hex = { version = "0.4", default-features = false }

[features]
default = ["std"]
std = ["engine-types/std","engine-sdk/std","engine-precompiles/std","engine-transactions/std"]
build_as_xtop_lib = []