[package]
name = "rustvm"
version = "0.1.0"
authors = ["charles"]
email = ["charles.liu@topnetwork.org"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = "1.0"
wasmer-wasi = "1.0.2"
wasmer-middlewares = "1.0.2"
wasmer-engine-jit = "1.0.2"
wasmer-compiler-singlepass = "1.0.2"
wasmer-compiler-cranelift = "1.0.2"
anyhow = "1.0"
thiserror = "1.0"
libc = "0.2.9"

[dev-dependencies]
wat = "1.0"

[lib]
crate-type = ["staticlib"]
name = "rustvm"